version: 2

sources: 
  - name: investimentos #nome que eu quero chamar
    schema: public #é o schema do meu banco de dados 
    description: dados que vieram da leitura dos meus pdfs #documentação
    tables: #cada uma das tabelas eu coloco os nomes
      - name: fatura_jornada
      - name: fatura_jornada_small
      - name: fatura_redrex
      - name: fatura_redrex_small